'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Form1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Adress_DB.Form1", GetType(Form1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=578,Y=17}.
        '''</summary>
        Friend Shared ReadOnly Property _WSL_AdressenDataSet_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("_WSL_AdressenDataSet.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=184,Y=57}.
        '''</summary>
        Friend Shared ReadOnly Property AdressenBindingSource_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("AdressenBindingSource.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=375,Y=57}.
        '''</summary>
        Friend Shared ReadOnly Property AdressenTableAdapter_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("AdressenTableAdapter.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property AdresstypLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("AdresstypLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property AdresstypLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("AdresstypLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property AnredeLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("AnredeLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property AnredeLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("AnredeLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=430,Y=142}.
        '''</summary>
        Friend Shared ReadOnly Property BelegeBindingSource_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BelegeBindingSource.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=785,Y=144}.
        '''</summary>
        Friend Shared ReadOnly Property BelegeMitAdresseBindingSource_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BelegeMitAdresseBindingSource.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=1034,Y=139}.
        '''</summary>
        Friend Shared ReadOnly Property BelegeMitAdresseTableAdapter_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BelegeMitAdresseTableAdapter.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=613,Y=142}.
        '''</summary>
        Friend Shared ReadOnly Property BelegeTableAdapter_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BelegeTableAdapter.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property BenutzerlisteToolStripMenuItem_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BenutzerlisteToolStripMenuItem.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property BTN_MapsSuche_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BTN_MapsSuche.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property BTN_ZuOutlook_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BTN_ZuOutlook.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property BundeslandLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("BundeslandLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property BundeslandLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("BundeslandLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property DatumLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DatumLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property DirekterKontaktLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DirekterKontaktLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=891,Y=97}.
        '''</summary>
        Friend Shared ReadOnly Property DocuwareCSVBindingSource_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("DocuwareCSVBindingSource.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=1111,Y=97}.
        '''</summary>
        Friend Shared ReadOnly Property DocuwareCSVTableAdapter_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("DocuwareCSVTableAdapter.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property DurchwahlLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DurchwahlLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property EinstellungenToolStripMenuItem_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EinstellungenToolStripMenuItem.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property EmailAddresseLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("EmailAddresseLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property EmailAddresseLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("EmailAddresseLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property EmailLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("EmailLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property FaxnummerLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("FaxnummerLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property FaxnummerLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("FaxnummerLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property FaxnummerLabel3_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("FaxnummerLabel3.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=767,Y=17}.
        '''</summary>
        Friend Shared ReadOnly Property FirmenNameBindingSource_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("FirmenNameBindingSource.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=980,Y=17}.
        '''</summary>
        Friend Shared ReadOnly Property FirmenNameTableAdapter_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("FirmenNameTableAdapter.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Friend Shared ReadOnly Property IDAdresse_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("IDAdresse.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property IDAdresseLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("IDAdresseLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Friend Shared ReadOnly Property IDKonto_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("IDKonto.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property IDKontoLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("IDKontoLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property IDKontoLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("IDKontoLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property IDLKontoLabel2_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("IDLKontoLabel2.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property JobtitleLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("JobtitleLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=167,Y=99}.
        '''</summary>
        Friend Shared ReadOnly Property KonfigurationBindingSource_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("KonfigurationBindingSource.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=390,Y=98}.
        '''</summary>
        Friend Shared ReadOnly Property KonfigurationTableAdapter_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("KonfigurationTableAdapter.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=550,Y=57}.
        '''</summary>
        Friend Shared ReadOnly Property KontakteBindingSource_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("KontakteBindingSource.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=27,Y=16}.
        '''</summary>
        Friend Shared ReadOnly Property KontakteMitAdresseBindingSource_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("KontakteMitAdresseBindingSource.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=271,Y=17}.
        '''</summary>
        Friend Shared ReadOnly Property KontakteMitAdresseTableAdapter_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("KontakteMitAdresseTableAdapter.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=729,Y=57}.
        '''</summary>
        Friend Shared ReadOnly Property KontakteTableAdapter_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("KontakteTableAdapter.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=1371,Y=17}.
        '''</summary>
        Friend Shared ReadOnly Property KontoBindingSource_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("KontoBindingSource.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=17,Y=57}.
        '''</summary>
        Friend Shared ReadOnly Property KontoTableAdapter_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("KontoTableAdapter.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property LandLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("LandLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property LandLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("LandLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=0,Y=143}.
        '''</summary>
        Friend Shared ReadOnly Property LogTabelleBindingSource_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("LogTabelleBindingSource.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=184,Y=148}.
        '''</summary>
        Friend Shared ReadOnly Property LogTabelleTableAdapter_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("LogTabelleTableAdapter.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=17,Y=97}.
        '''</summary>
        Friend Shared ReadOnly Property MenuStrip1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuStrip1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property MobiltelefonLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MobiltelefonLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property MobiltelefonLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MobiltelefonLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property NachnameLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("NachnameLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property NachnameLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("NachnameLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property OrtLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("OrtLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property OrtLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("OrtLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property PLZLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PLZLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property PLZLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PLZLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property PLZLabel2_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PLZLabel2.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property PositionLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PositionLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property PositionLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PositionLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property PostfachLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PostfachLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property PostfachLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PostfachLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=983,Y=55}.
        '''</summary>
        Friend Shared ReadOnly Property SachbearbeiterBindingSource_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("SachbearbeiterBindingSource.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property SachbearbeiterLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("SachbearbeiterLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=1188,Y=58}.
        '''</summary>
        Friend Shared ReadOnly Property SachbearbeiterTableAdapter_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("SachbearbeiterTableAdapter.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property StraßeLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("StraßeLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property StraßeLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("StraßeLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=1187,Y=17}.
        '''</summary>
        Friend Shared ReadOnly Property TableAdapterManager_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TableAdapterManager.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property TelefonGeschaeftlichLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("TelefonGeschaeftlichLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property TelefonGeschaeftlichLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("TelefonGeschaeftlichLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property TelefonPrivatLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("TelefonPrivatLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property TelefonPrivatLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("TelefonPrivatLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property ThemaLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ThemaLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property UStIdNrLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("UStIdNrLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property UStIdNrLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("UStIdNrLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property VonWemBesuchtLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("VonWemBesuchtLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property VornameLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("VornameLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property VornameLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("VornameLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property WebseiteLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("WebseiteLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property WebseiteLabel1_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("WebseiteLabel1.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property WeitereBesucherLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("WeitereBesucherLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Friend Shared ReadOnly Property WeitereKontakteLabel_GenerateMember() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("WeitereKontakteLabel.GenerateMember", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
    End Class
End Namespace
